# Generated by Django 5.0.4 on 2024-04-26 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('rasm', models.ImageField(upload_to='media')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('project_url', models.CharField(blank=True, max_length=200, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('dare', models.DateTimeField(auto_now=True)),
                ('turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfolder.type')),
            ],
        ),
    ]
