# Generated by Django 5.0.4 on 2024-05-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfolder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lavozimi', models.CharField(max_length=100)),
                ('malumot', models.TextField(blank=True, null=True)),
                ('twit_link', models.CharField(blank=True, max_length=200, null=True)),
                ('face_link', models.CharField(blank=True, max_length=200, null=True)),
                ('insta_link', models.CharField(blank=True, max_length=200, null=True)),
                ('in_link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
