# Generated by Django 5.0.4 on 2024-05-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfolder', '0003_services_rename_lavozimi_team_ishi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
