# Generated by Django 5.0.4 on 2024-05-06 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfolder', '0004_alter_portfolio_rasm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='rasm',
            new_name='chizma',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='name',
            new_name='ism',
        ),
    ]
