# Generated by Django 5.0.4 on 2024-05-08 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfolder', '0006_team_rasm_alter_portfolio_rasm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='text',
            new_name='Text',
        ),
    ]
