# Generated by Django 5.0.4 on 2024-05-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfolder', '0007_rename_name_portfolio_name_rename_text_team_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ism', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=90)),
                ('subject', models.CharField(max_length=70)),
                ('matn', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
